### ISSUE TITLE
Review systems across the world

### ISSUE THREAD

**Issue by Rainie34** [zatonovo/cadp_docs#2]
**Specific:** Review the application of the scientific method to analyze heat waves and their impact on public health. Evaluate challenges in data access, population outreach, and effectiveness of warning systems in the context of the two studies.
**Measurable:** Identify key data points, such as the number of heat warnings issued and excess mortality rates, and provide qualitative insights, including stakeholder perceptions and public awareness surveys.
**Achievable:** Compare meteorological vs. public health thresholds for warnings and analyze the reasoning behind differences.
**Relevant:** Focus on improving heat warning systems and Heat Action Plans (HAPs) to mitigate extreme heat impacts.
**Time-bound:** Complete by 09-23-2024, including spreadsheet comparison and conclusion on threshold differences.
[Review systems across the world (rich countriespoor countries).docx](https://github.com/user-attachments/files/17105121/Review.systems.across.the.world.rich.countriespoor.countries.docx)

**Comment by muxspace** [comment]
@Rainie34 it would be better to consolidate all the documents into a single document and synthesize the information. Remember the goal is to construct the survey questions. How does all this background reading inform the survey design, specifically the questions you want to ask? Perhaps you can use a web-based editor so it is easier to add comments as well.
