### ISSUE TITLE
Prototype Messaging Using Generative AI

### ISSUE THREAD

**Issue by Rainie34** [zatonovo/cadp_docs#4]
Specific: Create a series of heat risk warning messages utilizing generative AI techniques, focusing on zero-shot and one-shot learning to address various vulnerable populations.

Measurable: Address four key aspects of heat risk messaging: 
1) Explanation of zero-shot and one-shot learning; 
2) Heat risk warnings for different groups; 
3) Limitations of the messaging strategies; 
4) Effective communication practices.

Achievable: Employ generative AI tools to draft messages that are relevant and actionable for individuals at risk of heat-related illnesses.

Relevant: The messaging will target populations exposed to extreme heat, emphasizing public health awareness and safety.

Time-Bound: Complete the messaging prototypes and submit for review by 09-23-2024.
[Prototype Messaging Using Generative AI.docx](https://github.com/user-attachments/files/17105900/Prototype.Messaging.Using.Generative.AI.docx)

**Comment by muxspace** [comment]
@Rainie34 what is the methodology that you used? You need to provide more description to support your bullet points. It's unclear what exactly is in the document.

**Comment by muxspace** [comment]
As discussed the first question to answer is: Why is Prof Rowe asking me to research zero and one shot for this project?????

Once you can answer that confidently, then you can start to define the process for this test. And that's what this is. We're trying to answer some specific questions about the capability of LLMs. This means you need to identify the questions that need to be answered and then the hypotheses to test.

**Comment by muxspace** [comment]
@Rainie34 @vidhika-git

**Comment by muxspace** [comment]
The methodology needs to clearly describe the hypothesis and how you're testing the hypothesis. Then you need to present the results and provide a short assessment or evaluation on what you think the result of the test demonstrated, ie is the hypothesis correct or not?

**Comment by vidhika-git** [comment]
@muxspace  I think  you want us to look into zero-shot and one-shot learning because these approaches are key to understanding how well LLMs can generate effective heat risk messages without needing a lot of examples.

By exploring these concepts, we can figure out if the models can create relevant messages for different vulnerable groups during heat waves. Plus, we’ll get a sense of their strengths and weaknesses—like whether they can deliver clear, actionable advice in zero-shot scenarios or if they perform better with one example.

I’ll come up with specific questions to test how accurately they generate messages and check for any limitations around clarity and cultural sensitivity

**Comment by vidhika-git** [comment]
@muxspace 
Defining the process of testing 
**Step 1. Identifying the questions to be answered:**

1. How aware is the community of heat stress and its health impacts?
2. . What individual risk factors are most commonly recognized by different demographic groups?
3. How does access to cooling resources (like air conditioning and cooling centers) affect individuals’ preparedness for 
    extreme heat?
4. What are the gaps in knowledge regarding heat stress symptoms and preventive measures?

**step 2. Formulate Hypotheses:**
**Hypothesis 1**: A significant portion of the community lacks awareness of the symptoms of heat stress, which may increase their risk of heat-related illnesses during extreme heat events.

**Hypothesis 2.0:** Individuals with chronic health conditions (e.g., heart disease, diabetes) demonstrate a higher awareness of their susceptibility to heat stress than those without such conditions across all age groups.

**Hypothesis: 2.1** Women are more likely than men to acknowledge the risks associated with heat stress, particularly to pregnancy and caregiving responsibilities for vulnerable populations.

**Hypothesis 2.2** : Cultural and socioeconomic factors influence the recognition of individual risk factors for heat stress, with lower-income individuals showing less awareness compared to higher-income individuals.

**Hypothesis 3** : Access to cooling resources, such as air conditioning and nearby cooling centers, significantly enhances individuals’ preparedness for extreme heat, resulting in lower incidence rates of heat-related symptoms and higher confidence in managing heat exposure compared to those without such access.

**Hypothesis 4**: Many individuals, particularly younger populations, do not recognize the early symptoms of heat stress—such as dizziness and nausea—and have limited knowledge of effective preventive measures like hydration and appropriate clothing, leading to delayed responses and increased risk of severe health outcomes.

**Comment by Rainie34** [comment]
@muxspace please review
**Specific:** 10 types of heat risk-related questions were identified, zero-shot and one-shot answers were generated for each question, and a reusable template was created.

**Measurable:** 20 answers (10 zero-shot and 10 one-shot) were generated and their effectiveness and limitations were evaluated.

**Attainable:** Question identification, answer generation, and template creation were completed with existing resources to ensure that the results were feasible and completed within the specified time.

**Relevant:** The task helped validate the LLM's ability to respond to heat risk information and provide consistent and accurate recommendations for different user groups.

Timely: All tasks were completed within 1 week, including question identification, answer generation, and template design.
https://docs.google.com/document/d/17cf11mVxOZCc6T05APc2WG15Eww9ginGXROgG3XdyH4/edit
